name: Test Latest Published Version

on:
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.x'
      - name: Check Build Against Published
        run: |
          uv run --extra Testing .github/pyscripts/publish_check.py
