name: Automated Release

on:
  push:
    branches:
      - auto-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Version
        run: echo "PACKAGE_VERSION=v$(echo python setup.py --version)" >> $GITHUB_ENV
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ <PACKAGE_VERSION> }}
          body: Body release text
          files: README.txt
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
